[package]
name = "compact-bar-x"
version = "0.1.0"
authors = ["German David <germanmarinrolong@gmail.com>"]
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
colored = "2"
unicode-width = "0.1.8"
zellij-tile = "0.39.2"
zellij-tile-utils = "0.39.2"
