[package]
name = "compact-bar-x"
version = "0.1.0"
authors = ["German David <germanmarinrolong@gmail.com>"]
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
colored = "2.1.0"
unicode-width = "0.1.11"
zellij-tile = "0.40.0"
zellij-tile-utils = "0.40.0"
